# PHP + Apache
FROM phpstorm/php-apache:8.0-xdebug3.0

# Update OS and install common dev tools
RUN apt-get update
RUN apt-get install -y nano

# Install PHP extensions needed
RUN docker-php-ext-install -j$(nproc) mysqli pdo_mysql

# Set working directory to web files
WORKDIR /var/www/html